on: [push]
name: Build
jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: vault/plugins/artifactory
            asset_name: artifactory-secrets-plugin-linux-amd64
          - os: windows-latest
            artifact_name: vault/plugins/artifactory.exe
            asset_name: artifactory-secrets-plugin-windows-amd64.exe
          - os: macos-latest
            artifact_name: vault/plugins/artifactory
            asset_name: artifactory-secrets-plugin-darwin-amd64
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.14.x
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build
      run: go build -o ${{ matrix.artifact_name }} cmd/artifactory/main.go
    - name: Upload
      uses: actions/upload-artifact@v1
      with:
        name: ${{ matrix.asset_name }}
        path: ${{ matrix.artifact_name }}
  release:
    needs: [build]
    steps:
      - uses: "marvinpinto/action-automatic-release@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          files: |
            artifactory-secrets-plugin-linux-amd64
            artifactory-secrets-plugin-darwin-amd64
            artifactory-secrets-plugin-windows-amd64.exe

