on: [push]
name: Build
jobs:
  build:
    strategy:
      matrix:
        go-version: [1.14.x]
	platform: [ubnutu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/check@v2
    - name: Build
      run: go build -o vault/plugins/artifactory cmd/artifactory/main.go
